version: '3.8'

# 适用于已经有MySQL和Redis服务的环境
# 使用前请先配置 .env 文件中的数据库和Redis连接信息

services:
  app:
    image: marcosman/claude-code-relay:latest
    container_name: claude-code-relay-app
    restart: unless-stopped
    ports:
      - "10081:8080"
    env_file:
      - .env
    environment:
      # 确保时区设置正确
      TZ: Asia/Shanghai
    volumes:
      - app_logs:/app/logs
      # 如果使用SQLite，取消下面这行的注释
      # - app_data:/app/data
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # 安全配置
    security_opt:
      - no-new-privileges:true

volumes:
  app_logs:
    driver: local

networks:
  claude-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16